INSERT INTO EMPLOYEE (NAME, TITLE, MANAGER_ID) VALUES ('Kaushik', 'Ananthakrishnan', NULL);
INSERT INTO EMPLOYEE ( NAME, TITLE, MANAGER_ID) VALUES ('Jeff', 'Bezos', 1);
INSERT INTO EMPLOYEE (NAME, TITLE, MANAGER_ID) VALUES ('Bill', 'Gates', 1);