DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  TITLE VARCHAR(250) NOT NULL,
  MANAGER_ID INT NULL DEFAULT NULL,
  CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
);